services:
  - type: web
    name: puffingood-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: "/*"
        destination: /index.html
